version: '3.7'

services:
  demo-gateway-service:
    image: gmarino/demo-gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - prova-network

networks:
  prova-network:
