spring.application.name=demo-gateway
server.port=8765

# ==============================================================
# = EUREKA SERVER
# ==============================================================
eureka.client.serviceUrl.defaultZone= ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
eureka.client.serviceUrl.instance.preferIpAddress= true
# ==============================================================
# = DISCOVERY SERVICE
# ==============================================================
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

management.endpoints.web.exposure.include=health,info,gateway
